title: 随笔
description: My Personal Stack Problems
<<<<<<< HEAD
author: Sai Xie(Davie Angular)
=======
author: Xie Sai (Davie Angular)
>>>>>>> a22fabbd069eeb010754ce431fee174e5cc17bb3
github: https://github.com/xiesai
about:  Talk big, do it bigger<p>为年轻时吹过的牛逼而奋斗终身</p>
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/xiesai.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/xiesai"
    - icon: fa-github
      link: "https://github.com/xiesai"
    - icon: fa-weixin
      link: "#"
    - icon: fa-envelope
      link: "mailto:xiesai@huawei.com"
    - icon: fa-share-alt
      link: "https://github.com/xiesai"
share:
  twitter_username: agusmakmun6
  fb_appid: 1749788565247320

urls:
    - text: 关于
      url: /about/
    - text: 项目
      url: /projects/
    - text: contact
      url: /feed.xml

url: "https://xiesai.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
